### ISSUE TITLE
MissingMethodException when run against latest EFCore RC2 build

### ISSUE THREAD

**Issue by mmesdag** [efcore/EFCore.NamingConventions#155]
I pulled down the daily EFCore builds, and it seems like the changes to conventions there (PR [28601](https://github.com/dotnet/efcore/pull/28601)) have broken these, at least the `.UseSnakeCaseNamingConvention()` in my case. 

Whenever it's triggered (app startup, creating a migration), this error pops up: 

``System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IEntityTypeAddedConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_EntityTypeAddedConventions()'.
   at EFCore.NamingConventions.Internal.NamingConventionSetPlugin.ModifyConventions(ConventionSet conventionSet)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RuntimeConventionSetBuilder.CreateConventionSet()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)``

**Comment by roji** [comment]
You cannot mix versions by using the 6.0 version of EFCore.NamingConventions with a 7.0 prerelease version of EF Core. You'll have to wait until a 7.0 version of EFCore.NamingConventions is released.
