### ISSUE TITLE
UseSnakeCaseNamingConvention() Does not Handle Owned Entities Table in 5.0.0.rc

### ISSUE THREAD

**Issue by lajith111** [efcore/EFCore.NamingConventions#41]
For example, for a context like this

```

namespace Domain.Entities.Accounts
{
    public class Account : IEntity<int> 
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; } = null!;
     

        public AccountBalance AccountBalance { get; set; } = null!;   //Owned Type
      
    }


}
 public class AccountBalance //: IEntity<int>
   {    
       
     public Decimal? AuthorizedBalance { get; set; }
       

  }
	
 public void Configure(EntityTypeBuilder<Account> builder)
        {
            builder.ToTable("account",schema: "ops");
            builder.HasKey(a => a.Id);
          
            
            builder.OwnsOne(a => a.AccountBalance, ownedBuilder =>
            {
               
                ownedBuilder.WithOwner().HasForeignKey("AccountId");
                ownedBuilder.Property("AccountId").HasColumnName("account_id");
                ownedBuilder.ToTable("account_balance", schema: "ops");
               
            });

      }
```

When run  issue still persist in 5.0.0-rc.  After i run Update-Database -Context CBSContext

ther following error shown

```
Npgsql.PostgresException (0x80004005): 42P07: relation "pk_accounts" already exists
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "pk_accounts" already exists
    File: d:\pginstaller_13.auto\postgres.windows-x64\src\backend\catalog\index.c
    Line: 866
    Routine: index_create
42P07: relation "pk_accounts" already exists
```

If i remove options.UseSnakeCaseNamingConvention(); migration works fine ..

**Comment by lajith111** [comment]
if define owned entity with primary key migration works.. 

```
 builder.OwnsOne(a => a.AccountBalance, ownedBuilder =>
            {
                ownedBuilder.HasKey(b => b.Id);
                ownedBuilder.WithOwner().HasForeignKey("AccountId");
                ownedBuilder.Property("AccountId").HasColumnName("account_id");
                ownedBuilder.ToTable("account_balance", schema: "ops");
               
            });
```

**Comment by lajith111** [comment]
Sir any update on this package,.. Thanks

**Comment by roji** [comment]
Not yet - I plan to work on a 5.0.0 release of EFCore.NamingConventions in the coming week or so, and will try to look at this as well. Stay tuned.
