### ISSUE TITLE
Support multiple owned entities without table splitting

### ISSUE THREAD

**Issue by 4nonym0us** [efcore/EFCore.NamingConventions#67]
At this moment, EFCore.NamingConventions throws an exception if following conditions are met:
1. Owner entity is configured to have more then one owned entity without table splitting.
2. Table name of Owner entity is explicitly specified via `ToTable(name)` extension.

> System.InvalidOperationException. Cannot use table 'destination_table' for entity type 'Owner' since it is being used for entity type 'Owner.FirstOwned#Owned' and the name 'pk_destination_table' of the primary key {'Id'} does not match the name 'pk_owner' of the primary key {'OwnerId'}.
```
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IReadOnlyList`1 mappedTypes, String tableName, String schema, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Sqlite.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at EFCore.NamingConventions.Test.NameRewritingConventionTest.BuildModel(Action`1 builderAction, CultureInfo culture) in D:\git\EFCore.NamingConventions\EFCore.NamingConventions.Test\NameRewritingConventionTest.cs:line 339
   at EFCore.NamingConventions.Test.NameRewritingConventionTest.Multiple_owned_entities_without_table_splitting() in D:\git\EFCore.NamingConventions\EFCore.NamingConventions.Test\NameRewritingConventionTest.cs:line 308
```

Sample:
```csharp
[Fact]
public void Owned_entity_without_table_splitting_2()
{
    // throws System.InvalidOperationException
    BuildModel(b =>
    {
        var ownerBuilder = b.Entity<Owner>();
        ownerBuilder.OwnsOne(o => o.FirstOwned);
        ownerBuilder.OwnsOne(o => o.SecondOwned);
        ownerBuilder.ToTable("destination_table"); // <-- the test would be passed without this line
    });
}
```

```csharp
public class Owner
{
    public int Id { get; set; }
    public int OwnerProperty { get; set; }
    public Owned FirstOwned { get; set; }
    public Owned SecondOwned { get; set; }
}

public class Owned
{
    public int OwnedProperty { get; set; }
}
```

**Comment by roji** [comment]
Thanks for raising this! The bug actually wasn't related to having two owned entities, I managed to reproduce it with a simple:

```c#
var model = BuildModel(
    b => b.Entity<Owner>(
        e =>
        {
            e.OwnsOne(o => o.Owned);
            e.ToTable("destination_table");
        }));
```

... with the critical part being explicitly setting the owner's table after making the other entity owned.

**Comment by 4nonym0us** [comment]
Yeah, my bad, I ran multiple tests and just assumed that having multiple entities is the issue. For some reason I was pretty sure that somebody would've already reported the bug if it was caused by not having table name specified explicitly because this is a common use case.

Anyways, thanks for finding out what actually causes the exception and fixing it!

**Comment by roji** [comment]
No problem. Note this only occurs if the table name is set explicitly on the owner entity *after* the ownership relationship is configured... maybe that's a bit rare (or maybe not enough users are using this library :rofl:)

**Comment by 4nonym0us** [comment]
I see, so the bug is actually not as easy to reproduce as it looks like on the first glimpse.
The library is amazing and especially useful for RDBMs like PostgreSQL, thanks for maintaining it.

**Comment by roji** [comment]
Thanks for the kind words! Happy to know it's being used and is helpful :)

**Comment by phnx47** [comment]
When will it be published to nuget or any dev nuget?
