### ISSUE TITLE
Incorrect name for include properties for index

### ISSUE THREAD

**Issue by dimkadv2** [efcore/EFCore.NamingConventions#7]
When using the following design
```C#
public class AccountConfiguration : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> builder)
        {
            builder.HasIndex(x => new { x.OrganizationId, x.AccountName })
                .IncludeProperties(x => new
                {
                    x.FlatName,
                    x.FlatType,
                    x.GroupId,
                    x.HouseId,
                    x.RecipientId,
                    x.SuccessTries,
                    x.ValidationCode
                });
        }
    }

```
then we get the following migration code for the index

```C#
           migrationBuilder.CreateIndex(
                name: "IX_accounts_organization_id_account_name",
                table: "accounts",
                columns: new[] { "organization_id", "account_name" })
                .Annotation("Npgsql:IndexInclude", new[] { "FlatName", "FlatType", "GroupId", "HouseId", "RecipientId", "SuccessTries", "ValidationCode" });
```

```C#
            migrationBuilder.CreateTable(
                name: "accounts",
                columns: table => new
                {
                    id = table.Column<int>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo),
                    organization_id = table.Column<Guid>(nullable: false),
                    account_name = table.Column<string>(unicode: false, maxLength: 12, nullable: false),
                    flat_name = table.Column<string>(unicode: false, maxLength: 20, nullable: true),
                    flat_type = table.Column<string>(unicode: false, maxLength: 20, nullable: true),
                    validation_code = table.Column<string>(unicode: false, maxLength: 50, nullable: true),
                    group_id = table.Column<int>(nullable: true),
                    house_id = table.Column<int>(nullable: false),
                    recipient_id = table.Column<int>(nullable: false),
                    success_tries = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_accounts", x => x.id);
                    table.ForeignKey(
                        name: "FK_accounts_groups_group_id",
                        column: x => x.group_id,
                        principalTable: "groups",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_accounts_houses_house_id",
                        column: x => x.house_id,
                        principalTable: "houses",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_accounts_organization_organization_id",
                        column: x => x.organization_id,
                        principalTable: "organization",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_accounts_recipients_recipient_id",
                        column: x => x.recipient_id,
                        principalTable: "recipients",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });
```

there is an error installing migration
when using the ToTable extension, the table name does not change

**Comment by roji** [comment]
Can you please post the error? Also, can you please include a minimal model, before and after the migration, so I can reproduce the issue?

**Comment by dimkadv2** [comment]
Hi,  here is the code that demonstrates the problem
```C#
    public class Account
    {
        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }
    }

    public class AccountConfig : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> builder)
        {
            builder.HasKey(x => x.Id);

            builder.HasIndex(x => x.Id)
                .IncludeProperties(x => new
                {
                    x.FirstName,
                    x.LastName
                });
        }
    }

    public class AccountContext : DbContext
    {
        public DbSet<Account> Accounts { get; set; }

        public AccountContext()
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            optionsBuilder
                .UseNpgsql("Host=localhost;port=5432;Database=test;Username=postgres;")
                .UseSnakeCaseNamingConvention();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

            base.OnModelCreating(modelBuilder);
        }
    }
```

Migration:

```C#
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "accounts",
                columns: table => new
                {
                    id = table.Column<int>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(nullable: true),
                    last_name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_accounts", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_accounts_id",
                table: "accounts",
                column: "id")
                .Annotation("Npgsql:IndexInclude", new[] { "FirstName", "LastName" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "accounts");
        }
    }
```

when call "Update-Database" get exception:

`Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX "IX_accounts_id" ON accounts (id) INCLUDE ("Firstname", "Lastname");
Npgsql.PostgresException (0x80004005): 42703: column "Firstname" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42703
    MessageText: column "Firstname" does not exist
    File: indexcmds.c
    Line: 1582
    Routine: ComputeIndexAttrs
42703: column "Firstname" does not exist`

Because properties Firstname and Lastname rename to first_name and last_name.

Thanks!

**Comment by roji** [comment]
Thanks, I can the exception happening. As a workaround, if you remove `UseSnakeCaseNamingConvention` it will work - but I will definitely look at resolving this for 3.1.1.

**Comment by roji** [comment]
This is actually a provider in the provider and not with this plugin - changing the column name manually also triggers the exception. Replacing this with https://github.com/npgsql/efcore.pg/issues/1201.
